services:
  backend:
    image: rajverma4/charity-backend:latest
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: rajverma4/charity-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
